build:
	go build -o ${GOPATH}/bin/delete delete.go;
	go build -o ${GOPATH}/bin/dumptable dumptable.go;
	go build -o ${GOPATH}/bin/insert insert.go;
	go build -o ${GOPATH}/bin/join join.go;
	go build -o ${GOPATH}/bin/lookup lookup.go;
	go build -o ${GOPATH}/bin/printring printring.go;
	go build -o ${GOPATH}/bin/replic replic.go;
	go build -o ${GOPATH}/bin/search search.go;
	go build -o ${GOPATH}/bin/update update.go;
